package com.minhnb.finvera_be.alert.service;
import static com.minhnb.finvera_be.alert.dto.AlertDtos.*;import tools.jackson.databind.JsonNode;import com.minhnb.finvera_be.alert.domain.AlertDomain;import com.minhnb.finvera_be.alert.entity.*;import com.minhnb.finvera_be.alert.repository.*;import com.minhnb.finvera_be.market.service.MarketReferenceDataService;import com.minhnb.finvera_be.portfolio.service.PortfolioAlertDataService;import jakarta.persistence.EntityManager;import java.time.*;import java.util.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.*;
@Service public class AlertManagementService{
 private final AlertDefinitionRepository defs;private final AlertEvaluationRepository evals;private final MarketReferenceDataService market;private final PortfolioAlertDataService portfolios;private final OwnerScopedAlertAccess access;private final EntityManager entityManager;private final Clock clock;
 public AlertManagementService(AlertDefinitionRepository d,AlertEvaluationRepository e,MarketReferenceDataService m,PortfolioAlertDataService p,OwnerScopedAlertAccess a,EntityManager em,Clock c){defs=d;evals=e;market=m;portfolios=p;access=a;entityManager=em;clock=c;}
 @Transactional public AlertResponse create(CreateAlertRequest request){UUID owner=access.getAuthenticatedOwnerId();lockQuota(owner);if(defs.countByOwnerIdAndDeletedAtIsNull(owner)>=100||defs.countByOwnerIdAndEnabledTrueAndDeletedAtIsNull(owner)>=50)throw new AlertExceptions.AlertQuotaException("ALERT_QUOTA_REACHED");JsonNode condition=request.condition().deepCopy();AlertDomain.Type type;try{type=AlertDomain.normalize(condition);}catch(IllegalArgumentException e){throw new AlertExceptions.AlertValidationException(e.getMessage());}validateTarget(owner,type,condition);Instant now=clock.instant();return map(defs.save(new AlertDefinitionEntity(UUID.randomUUID(),owner,request.name().trim(),type.name(),condition,AlertDomain.summary(condition),now)));}
 @Transactional(readOnly=true)public PageResponse<AlertResponse> list(int limit,int offset){UUID o=access.getAuthenticatedOwnerId();var p=defs.findByOwnerIdAndDeletedAtIsNullOrderByCreatedAtDescIdDesc(o,OffsetPageRequest.of(offset,limit));return new PageResponse<>(p.getContent().stream().map(this::map).toList(),p.getTotalElements(),limit,offset);}
 @Transactional(readOnly=true)public AlertResponse get(UUID id){return map(owned(id));}
 @Transactional public AlertResponse state(UUID id,boolean enabled){var a=owned(id);if(enabled==a.isEnabled())return map(a);UUID o=a.getOwnerId();if(enabled){lockQuota(o);if(defs.countByOwnerIdAndEnabledTrueAndDeletedAtIsNull(o)>=50)throw new AlertExceptions.AlertQuotaException("ENABLED_ALERT_QUOTA_REACHED");}a.setEnabled(enabled,clock.instant());return map(a);}
 @Transactional public void delete(UUID id){owned(id).delete(clock.instant());}
 @Transactional(readOnly=true)public PageResponse<EvaluationResponse> evaluations(UUID id,int limit,int offset){var a=owned(id);var p=evals.findByAlertIdOrderByEvaluatedAtDescIdDesc(a.getId(),OffsetPageRequest.of(offset,limit));return new PageResponse<>(p.getContent().stream().map(AlertManagementService::mapEval).toList(),p.getTotalElements(),limit,offset);}
 private void lockQuota(UUID owner){entityManager.createNativeQuery("select pg_advisory_xact_lock(hashtextextended(cast(?1 as text), 0))").setParameter(1,owner.toString()).getSingleResult();}
 private AlertDefinitionEntity owned(UUID id){return defs.findByIdAndOwnerIdAndDeletedAtIsNull(id,access.getAuthenticatedOwnerId()).orElseThrow(AlertExceptions.AlertNotFoundException::new);}
 private void validateTarget(UUID owner,AlertDomain.Type type,JsonNode c){if(c.hasNonNull("symbol")&&market.findActiveInstrumentBySymbol(AlertDomain.symbol(c)).isEmpty())throw new AlertExceptions.AlertValidationException("SYMBOL_NOT_AVAILABLE");if(type==AlertDomain.Type.PORTFOLIO_CONCENTRATION_ABOVE&&!portfolios.existsOwned(owner,UUID.fromString(c.get("portfolioId").asText())))throw new AlertExceptions.AlertValidationException("TARGET_NOT_AVAILABLE");}
 private AlertResponse map(AlertDefinitionEntity a){var latest=evals.findFirstByAlertIdOrderByEvaluatedAtDescIdDesc(a.getId()).map(AlertManagementService::mapEval).orElse(null);return new AlertResponse(a.getId(),a.getName(),a.getConditionPayload(),a.getConditionVersion(),a.getConditionSummary(),a.isEnabled(),a.getEpisodeState(),latest,a.getLastTriggeredAt(),a.getLastDeliveryOutcome(),a.getCreatedAt(),a.getUpdatedAt());}
 static EvaluationResponse mapEval(AlertEvaluationEntity e){return new EvaluationResponse(e.getId(),e.getOutcome(),e.getReasonCode(),e.getFactAt(),e.getAcceptedAt(),e.getEvaluatedAt(),e.getAttemptCount(),e.getEvidence());}
}
