package com.minhnb.finvera_be.alert.service;
import com.minhnb.finvera_be.alert.domain.AlertDomain;import com.minhnb.finvera_be.alert.domain.AlertDomain.*;import com.minhnb.finvera_be.alert.entity.AlertDefinitionEntity;import com.minhnb.finvera_be.market.service.*;import com.minhnb.finvera_be.portfolio.service.PortfolioAlertDataService;import com.minhnb.finvera_be.research.domain.DocumentType;import com.minhnb.finvera_be.research.service.ResearchAlertDataService;import com.minhnb.finvera_be.stock.service.*;import java.math.*;import java.time.*;import java.util.*;import tools.jackson.databind.*;import tools.jackson.databind.node.ObjectNode;import org.springframework.stereotype.Service;
@Service public class AlertFactResolver{
 private static final ZoneId VN=ZoneId.of("Asia/Ho_Chi_Minh");private final MarketReferenceDataService market;private final MarketAlertDataService regimes;private final StockAlertDataService stocks;private final PortfolioAlertDataService portfolios;private final ResearchAlertDataService research;private final ObjectMapper json;private final Clock clock;
 public AlertFactResolver(MarketReferenceDataService m,MarketAlertDataService rg,StockAlertDataService s,PortfolioAlertDataService p,ResearchAlertDataService r,ObjectMapper j,Clock c){market=m;regimes=rg;stocks=s;portfolios=p;research=r;json=j;clock=c;}
 public Decision resolve(AlertDefinitionEntity a){JsonNode c=a.getConditionPayload();Type type=Type.valueOf(a.getConditionType());if(type==Type.MARKET_REGIME_CHANGE)return regime(c);if(type==Type.PORTFOLIO_CONCENTRATION_ABOVE)return portfolio(a,c);if(type==Type.NEW_DOCUMENT)return document(a,c);var inst=market.findActiveInstrumentBySymbol(AlertDomain.symbol(c));if(inst.isEmpty())return withheld("SYMBOL_NOT_AVAILABLE","symbol",clock.instant());var snap=stocks.resolve(inst.get().instrumentId());if(snap.bars().isEmpty())return withheld("PRICE_DATA_MISSING","stock",clock.instant());var bars=snap.bars();var cur=bars.getLast();if(market.countTradingSessionsBetween(inst.get().venue(),cur.date(),LocalDate.now(clock.withZone(VN)))>1)return withheld("PRICE_DATA_STALE",cur.id().toString(),cur.acceptedAt());String requested=c.hasNonNull("adjustmentBasis")?c.get("adjustmentBasis").asText():cur.basis();if(requested!=null&&!Objects.equals(requested,cur.basis()))return withheld("ADJUSTMENT_BASIS_MISMATCH",cur.id().toString(),cur.acceptedAt());if(Set.of(Type.VOLUME_SPIKE,Type.BREAKOUT,Type.BREAKDOWN).contains(type)&&bars.stream().anyMatch(x->!Objects.equals(cur.basis(),x.basis())))return withheld("ADJUSTMENT_BASIS_MISMATCH",cur.id().toString(),cur.acceptedAt());return switch(type){
  case PRICE_ABOVE,PRICE_BELOW->compare(type==Type.PRICE_ABOVE,cur.close(),AlertDomain.decimal(c,"threshold"),cur,"VND_PER_SHARE","daily-bar-v1");
  case RSI_ABOVE,RSI_BELOW->indicatorThreshold(type,c,snap,cur);
  case MACD_BULLISH_CROSS,MACD_BEARISH_CROSS->macd(type,snap,cur);
  case MA_BULLISH_CROSS,MA_BEARISH_CROSS->ma(type,c,snap,cur);
  case VOLUME_SPIKE->volume(c,bars,cur);case BREAKOUT,BREAKDOWN->breakout(type,bars,cur);
  case STRATEGY_SIGNAL->signal(c,snap,cur);default->throw new IllegalStateException();};}
 private Decision indicatorThreshold(Type t,JsonNode c,StockAlertDataService.Snapshot s,StockAlertDataService.Bar b){var i=latest(s,"RSI14");if(i==null)return withheld("INDICATOR_MISSING",b.id().toString(),b.acceptedAt());var invalid=invalidIndicator(i,b);if(invalid!=null)return invalid;BigDecimal v=i.components().get("VALUE");if(v==null)return withheld("INDICATOR_MISSING",i.id().toString(),i.acceptedAt());return compare(t==Type.RSI_ABOVE,v,AlertDomain.decimal(c,"threshold"),b,"INDEX",i.ruleVersion());}
 private Decision macd(Type t,StockAlertDataService.Snapshot s,StockAlertDataService.Bar b){var pair=latestTwo(s,"MACD");if(pair.size()<2||s.bars().size()<2)return withheld("PRIOR_OBSERVATION_MISSING",b.id().toString(),b.acceptedAt());var old=pair.get(0);var now=pair.get(1);var invalid=invalidIndicator(now,b);if(invalid!=null)return invalid;LocalDate previousDate=s.bars().get(s.bars().size()-2).date();if(!"CURRENT".equals(old.status())||!old.date().equals(previousDate)||!Objects.equals(old.basis(),now.basis()))return withheld("INDICATOR_COHERENCE_MISMATCH",now.id().toString(),now.acceptedAt());BigDecimal om=old.components().get("MACD_LINE"),os=old.components().get("SIGNAL"),nm=now.components().get("MACD_LINE"),ns=now.components().get("SIGNAL");if(Stream.of(om,os,nm,ns).anyMatch(Objects::isNull))return withheld("INDICATOR_MISSING",now.id().toString(),now.acceptedAt());boolean bullish=t==Type.MACD_BULLISH_CROSS;boolean hit=bullish?om.compareTo(os)<=0&&nm.compareTo(ns)>0:om.compareTo(os)>=0&&nm.compareTo(ns)<0;return decision(hit,now.id().toString(),at(now.date()),now.acceptedAt(),evidence(nm,ns,"INDEX",now.ruleVersion()),null);}
 private Decision ma(Type t,JsonNode c,StockAlertDataService.Snapshot s,StockAlertDataService.Bar b){String sc="MA"+c.get("shortWindow").asInt(),lc="MA"+c.get("longWindow").asInt();var sp=latestTwo(s,sc);var lp=latestTwo(s,lc);if(sp.size()<2||lp.size()<2||s.bars().size()<2)return withheld("PRIOR_OBSERVATION_MISSING",b.id().toString(),b.acceptedAt());var invalid=invalidIndicator(sp.get(1),b);if(invalid!=null)return invalid;invalid=invalidIndicator(lp.get(1),b);if(invalid!=null)return invalid;LocalDate previousDate=s.bars().get(s.bars().size()-2).date();if(!"CURRENT".equals(sp.get(0).status())||!"CURRENT".equals(lp.get(0).status())||!sp.get(0).date().equals(previousDate)||!lp.get(0).date().equals(previousDate)||!sp.get(1).date().equals(lp.get(1).date())||!Objects.equals(sp.get(0).basis(),b.basis())||!Objects.equals(lp.get(0).basis(),b.basis()))return withheld("INDICATOR_COHERENCE_MISMATCH",b.id().toString(),b.acceptedAt());BigDecimal so=sp.get(0).components().get("VALUE"),sn=sp.get(1).components().get("VALUE"),lo=lp.get(0).components().get("VALUE"),ln=lp.get(1).components().get("VALUE");if(Stream.of(so,sn,lo,ln).anyMatch(Objects::isNull))return withheld("INDICATOR_MISSING",b.id().toString(),b.acceptedAt());boolean bull=t==Type.MA_BULLISH_CROSS;boolean hit=bull?so.compareTo(lo)<=0&&sn.compareTo(ln)>0:so.compareTo(lo)>=0&&sn.compareTo(ln)<0;return decision(hit,sp.get(1).id()+":"+lp.get(1).id(),at(sp.get(1).date()),sp.get(1).acceptedAt(),evidence(sn,ln,"VND_PER_SHARE",sp.get(1).ruleVersion()),null);}
 private Decision volume(JsonNode c,List<StockAlertDataService.Bar> bars,StockAlertDataService.Bar cur){if(bars.size()<21)return withheld("INSUFFICIENT_HISTORY",cur.id().toString(),cur.acceptedAt());var prior=bars.subList(bars.size()-21,bars.size()-1);BigDecimal avg=prior.stream().map(x->BigDecimal.valueOf(x.volume())).reduce(BigDecimal.ZERO,BigDecimal::add).divide(new BigDecimal("20"),12,RoundingMode.HALF_UP);BigDecimal threshold=avg.multiply(AlertDomain.decimal(c,"threshold"));return compare(true,BigDecimal.valueOf(cur.volume()),threshold,cur,"SHARES","volume-spike-v1");}
 private Decision breakout(Type t,List<StockAlertDataService.Bar> bars,StockAlertDataService.Bar cur){if(bars.size()<22)return withheld("INSUFFICIENT_HISTORY",cur.id().toString(),cur.acceptedAt());int n=bars.size();var prior20=bars.subList(n-21,n-1);var previous20=bars.subList(n-22,n-2);boolean up=t==Type.BREAKOUT;BigDecimal boundary=up?prior20.stream().map(StockAlertDataService.Bar::high).max(BigDecimal::compareTo).orElseThrow():prior20.stream().map(StockAlertDataService.Bar::low).min(BigDecimal::compareTo).orElseThrow();BigDecimal oldBoundary=up?previous20.stream().map(StockAlertDataService.Bar::high).max(BigDecimal::compareTo).orElseThrow():previous20.stream().map(StockAlertDataService.Bar::low).min(BigDecimal::compareTo).orElseThrow();BigDecimal prev=bars.get(n-2).close();boolean hit=up?prev.compareTo(oldBoundary)<=0&&cur.close().compareTo(boundary)>0:prev.compareTo(oldBoundary)>=0&&cur.close().compareTo(boundary)<0;return decision(hit,cur.id().toString(),at(cur.date()),cur.acceptedAt(),evidence(cur.close(),boundary,"VND_PER_SHARE","breakout-v1"),null);}
 private Decision signal(JsonNode c,StockAlertDataService.Snapshot s,StockAlertDataService.Bar b){String code=c.get("strategyCode").asText();var match=s.signals().stream().filter(x->x.strategyCode().equals(code)&&x.asOfTradingDate().equals(b.date())).findFirst();if(match.isEmpty())return withheld("STRATEGY_SIGNAL_NOT_PUBLISHED","signal:"+b.id()+":"+code,b.acceptedAt());var x=match.get();return decision(true,x.id().toString(),at(x.asOfTradingDate()),x.calculatedAt(),evidence(x.entryLow(),x.entryHigh(),"VND_PER_SHARE",x.ruleVersion()),x.id().toString());}
 private Decision regime(JsonNode c){var p=regimes.latestPair();if(p.size()<2)return withheld("PRIOR_OBSERVATION_MISSING","regime",clock.instant());var now=p.get(0);var old=p.get(1);if(!"CURRENT".equals(now.status())||!"CURRENT".equals(old.status()))return withheld("REGIME_UNAVAILABLE",now.id().toString(),now.acceptedAt());if(market.countTradingSessionsBetween("HOSE",now.date(),LocalDate.now(clock.withZone(VN)))>1)return withheld("REGIME_DATA_STALE",now.id().toString(),now.acceptedAt());boolean hit=!Objects.equals(old.label(),now.label())&&Objects.equals(c.get("targetLabel").asText(),now.label());return decision(hit,now.id().toString(),now.observedAt(),now.acceptedAt(),evidenceText(old.label(),now.label(),"REGIME",now.ruleVersion()),null);}
 private Decision portfolio(AlertDefinitionEntity a,JsonNode c){var s=portfolios.resolve(a.getOwnerId(),UUID.fromString(c.get("portfolioId").asText()));if(s.percentage()==null)return withheld(s.reason(),s.factKey(),s.observedAt());boolean hit=s.percentage().compareTo(AlertDomain.decimal(c,"thresholdPercent"))>=0;return decision(hit,s.factKey(),s.observedAt(),s.observedAt(),evidence(s.percentage(),AlertDomain.decimal(c,"thresholdPercent"),"PERCENT",s.ruleVersion()),null);}
 private Decision document(AlertDefinitionEntity a,JsonNode c){var i=market.findInstrumentBySymbolIncludingDelisted(AlertDomain.symbol(c));if(i.isEmpty())return withheld("SYMBOL_NOT_AVAILABLE","document",clock.instant());UUID instrument=i.get().instrumentId();DocumentType type=null;if(c.hasNonNull("documentType"))try{type=DocumentType.valueOf(c.get("documentType").asText());}catch(Exception e){return withheld("DOCUMENT_TYPE_UNSUPPORTED","document",clock.instant());}boolean hasCursor=a.getLastFactAt()!=null&&!a.getLastFactAt().isBefore(a.getBaselineAt())&&a.getLastFactKey()!=null;Instant after=hasCursor?a.getLastFactAt():a.getBaselineAt();UUID afterId=null;if(hasCursor)try{afterId=UUID.fromString(a.getLastFactKey());}catch(IllegalArgumentException ignored){}var list=research.findAfter(a.getOwnerId(),instrument,type,after,afterId,1);if(list.isEmpty()){String cursorKey=afterId==null?"document-baseline:"+after:afterId.toString();return decision(false,cursorKey,after,after,evidenceText(null,null,"EVENT","research-document-v1"),null);}var d=list.getFirst();return decision(true,d.id().toString(),d.acceptedAt(),d.acceptedAt(),evidenceText(d.category(),d.title(),"DOCUMENT","research-document-v1"),d.id().toString());}
 private Decision compare(boolean above,BigDecimal v,BigDecimal threshold,StockAlertDataService.Bar b,String unit,String version){boolean hit=above?v.compareTo(threshold)>=0:v.compareTo(threshold)<=0;return decision(hit,b.id().toString(),at(b.date()),b.acceptedAt(),evidence(v,threshold,unit,version),null);}
 private StockAlertDataService.Indicator latest(StockAlertDataService.Snapshot s,String code){return s.indicators().stream().filter(x->x.code().equals(code)).max(Comparator.comparing(StockAlertDataService.Indicator::date)).orElse(null);}private List<StockAlertDataService.Indicator> latestTwo(StockAlertDataService.Snapshot s,String code){var matching=s.indicators().stream().filter(x->x.code().equals(code)).sorted(Comparator.comparing(StockAlertDataService.Indicator::date)).toList();return matching.size()<=2?matching:matching.subList(matching.size()-2,matching.size());}
 private Decision invalidIndicator(StockAlertDataService.Indicator i,StockAlertDataService.Bar b){if(!"CURRENT".equals(i.status()))return withheld(i.reason()==null?"INDICATOR_UNAVAILABLE":i.reason(),i.id().toString(),i.acceptedAt());if(!i.date().equals(b.date()))return withheld("INDICATOR_STALE",i.id().toString(),i.acceptedAt());if(!Objects.equals(i.basis(),b.basis()))return withheld("ADJUSTMENT_BASIS_MISMATCH",i.id().toString(),i.acceptedAt());return null;}
 private Decision decision(boolean hit,String key,Instant fact,Instant accepted,ObjectNode e,String event){return new Decision(hit?Outcome.TRUE:Outcome.FALSE,null,e,key,fact,accepted,event);}private Decision withheld(String reason,String key,Instant accepted){return new Decision(Outcome.WITHHELD,reason,evidenceText(null,null,"UNKNOWN","alert-condition-v1"),key,accepted,accepted,null);}
 private ObjectNode evidence(BigDecimal value,BigDecimal threshold,String unit,String version){ObjectNode n=json.createObjectNode();if(value!=null)n.put("observedValue",value.toPlainString());if(threshold!=null)n.put("threshold",threshold.toPlainString());n.put("unit",unit);n.put("ruleVersion",version);return n;}private ObjectNode evidenceText(String from,String to,String unit,String version){ObjectNode n=json.createObjectNode();if(from!=null)n.put("from",from);if(to!=null)n.put("to",to);n.put("unit",unit);n.put("ruleVersion",version);return n;}private static Instant at(LocalDate d){return d.atTime(15,0).atZone(VN).toInstant();}
 private static final class Stream{static java.util.stream.Stream<BigDecimal> of(BigDecimal...x){return Arrays.stream(x);}}
}
