package com.minhnb.finvera_be.backtest;
import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.csrf;import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;import static org.mockito.Mockito.verifyNoInteractions;
import com.minhnb.finvera_be.auth.config.OwnerSecurityConfiguration;import com.minhnb.finvera_be.auth.controller.OwnerAccessController;import com.minhnb.finvera_be.auth.service.OwnerSessionService;import com.minhnb.finvera_be.backtest.controller.BacktestController;import com.minhnb.finvera_be.backtest.service.*;import java.util.UUID;import org.junit.jupiter.api.Test;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.webmvc.test.autoconfigure.WebMvcTest;import org.springframework.context.annotation.Import;import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;import org.springframework.test.context.DynamicPropertyRegistry;import org.springframework.test.context.DynamicPropertySource;import org.springframework.test.context.bean.override.mockito.MockitoBean;import org.springframework.test.web.servlet.MockMvc;
@WebMvcTest(controllers={OwnerAccessController.class,BacktestController.class}) @Import({OwnerSecurityConfiguration.class,OwnerSessionService.class})
class BacktestSecurityTests{
 static final String OWNER="owner-"+UUID.randomUUID(),PASSWORD=UUID.randomUUID().toString(),HASH=new BCryptPasswordEncoder(4).encode(PASSWORD);@DynamicPropertySource static void props(DynamicPropertyRegistry r){r.add("finvera.security.owner.id",()->"00000000-0000-0000-0000-000000000001");r.add("finvera.security.owner.username",()->OWNER);r.add("finvera.security.owner.password-hash",()->HASH);}
 @Autowired MockMvc mvc;@MockitoBean BacktestCommandService commands;@MockitoBean BacktestQueryService queries;
 @Test void everyReadRouteRequiresOwnerSession()throws Exception{String id=UUID.randomUUID().toString();for(String path:new String[]{"/api/v1/backtests","/api/v1/backtests/"+id,"/api/v1/backtests/"+id+"/trades","/api/v1/backtests/"+id+"/equity","/api/v1/backtests/"+id+"/events"})mvc.perform(get(path)).andExpect(status().isUnauthorized());verifyNoInteractions(queries);}
 @Test void createRequiresSessionAndCsrf()throws Exception{mvc.perform(post("/api/v1/backtests").with(csrf()).contentType("application/json").content("{}" )).andExpect(status().isUnauthorized());var login=mvc.perform(post("/api/v1/auth/session").with(csrf()).contentType("application/json").content("{\"username\":\""+OWNER+"\",\"password\":\""+PASSWORD+"\"}")).andExpect(status().isNoContent()).andReturn();var session=(org.springframework.mock.web.MockHttpSession)login.getRequest().getSession(false);mvc.perform(post("/api/v1/backtests").session(session).contentType("application/json").content("{}" )).andExpect(status().isForbidden());verifyNoInteractions(commands);}
}
