package com.minhnb.finvera_be.alert.entity;
import tools.jackson.databind.JsonNode;import jakarta.persistence.*;import java.time.Instant;import java.util.UUID;import org.hibernate.annotations.JdbcTypeCode;import org.hibernate.type.SqlTypes;
@Entity @Table(name="alert_definition")
public class AlertDefinitionEntity{
 @Id private UUID id;@Column(name="owner_id")private UUID ownerId;private String name;@Column(name="condition_type")private String conditionType;@Column(name="condition_version")private String conditionVersion;
 @JdbcTypeCode(SqlTypes.JSON)@Column(name="condition_payload",columnDefinition="jsonb")private JsonNode conditionPayload;@Column(name="condition_summary")private String conditionSummary;
 private boolean enabled;@Column(name="episode_state")private String episodeState;@Column(name="episode_sequence")private long episodeSequence;@Column(name="baseline_at")private Instant baselineAt;
 @Column(name="last_fact_key")private String lastFactKey;@Column(name="last_fact_at")private Instant lastFactAt;@Column(name="last_evaluated_at")private Instant lastEvaluatedAt;@Column(name="last_outcome")private String lastOutcome;@Column(name="last_reason_code")private String lastReasonCode;@Column(name="last_triggered_at")private Instant lastTriggeredAt;@Column(name="last_delivery_outcome")private String lastDeliveryOutcome;
 @Column(name="next_evaluation_at")private Instant nextEvaluationAt;@Column(name="lease_token")private UUID leaseToken;@Column(name="lease_until")private Instant leaseUntil;@Column(name="attempt_count")private short attemptCount;@Version@Column(name="row_version")private long rowVersion;@Column(name="created_at")private Instant createdAt;@Column(name="updated_at")private Instant updatedAt;@Column(name="deleted_at")private Instant deletedAt;
 protected AlertDefinitionEntity(){} public AlertDefinitionEntity(UUID id,UUID ownerId,String name,String type,JsonNode payload,String summary,Instant now){this.id=id;this.ownerId=ownerId;this.name=name;conditionType=type;conditionVersion="alert-condition-v1";conditionPayload=payload;conditionSummary=summary;enabled=true;episodeState="UNKNOWN";baselineAt=now;nextEvaluationAt=now;createdAt=now;updatedAt=now;}
 public UUID getId(){return id;}public UUID getOwnerId(){return ownerId;}public String getName(){return name;}public String getConditionType(){return conditionType;}public String getConditionVersion(){return conditionVersion;}public JsonNode getConditionPayload(){return conditionPayload;}public String getConditionSummary(){return conditionSummary;}public boolean isEnabled(){return enabled;}public String getEpisodeState(){return episodeState;}public long getEpisodeSequence(){return episodeSequence;}public Instant getBaselineAt(){return baselineAt;}public String getLastFactKey(){return lastFactKey;}public Instant getLastFactAt(){return lastFactAt;}public Instant getLastEvaluatedAt(){return lastEvaluatedAt;}public String getLastOutcome(){return lastOutcome;}public String getLastReasonCode(){return lastReasonCode;}public Instant getLastTriggeredAt(){return lastTriggeredAt;}public String getLastDeliveryOutcome(){return lastDeliveryOutcome;}public Instant getNextEvaluationAt(){return nextEvaluationAt;}public UUID getLeaseToken(){return leaseToken;}public Instant getLeaseUntil(){return leaseUntil;}public short getAttemptCount(){return attemptCount;}public Instant getCreatedAt(){return createdAt;}public Instant getUpdatedAt(){return updatedAt;}public Instant getDeletedAt(){return deletedAt;}
 public void setEnabled(boolean value,Instant now){enabled=value;updatedAt=now;leaseToken=null;leaseUntil=null;attemptCount=0;if(value){episodeState="UNKNOWN";baselineAt=now;nextEvaluationAt=now;}else nextEvaluationAt=null;}
 public void delete(Instant now){setEnabled(false,now);deletedAt=now;}
 public void claim(UUID token,Instant until){leaseToken=token;leaseUntil=until;attemptCount++;}
 public void holdLease(Instant until){leaseUntil=until;}
 public void complete(String factKey,Instant factAt,String outcome,String reason,Instant now,Instant next){lastFactKey=factKey;lastFactAt=factAt;lastEvaluatedAt=now;lastOutcome=outcome;lastReasonCode=reason;nextEvaluationAt=next;leaseToken=null;leaseUntil=null;attemptCount=0;updatedAt=now;}
 public long trigger(Instant now){episodeState="TRUE";episodeSequence++;lastTriggeredAt=now;lastDeliveryOutcome="DELIVERED";return episodeSequence;}public void falseState(){episodeState="FALSE";}public void releaseForRetry(Instant next){leaseToken=null;leaseUntil=null;nextEvaluationAt=next;}public void clearExpiredLease(Instant next){leaseToken=null;leaseUntil=null;nextEvaluationAt=next;}
}
