import { getCsrf } from "../../auth/api/owner-access";
export const STRATEGIES=["TREND_FOLLOWING","MOMENTUM","BREAKOUT","PULLBACK","MEAN_REVERSION","MA_CROSSOVER","MACD_BASED","RSI_BASED"] as const;
const RUN_STATUSES=["QUEUED","RUNNING","COMPLETED","WITHHELD","FAILED"] as const;
const METRIC_CODES=["TOTAL_RETURN","CAGR","WIN_RATE","PROFIT_FACTOR","MAXIMUM_DRAWDOWN","SHARPE_RATIO","AVERAGE_TRADE_RETURN","TRADE_COUNT"] as const;
const METRIC_UNITS=["RATE","RATIO","COUNT"] as const;
const AVAILABILITIES=["DEFINED","UNAVAILABLE"] as const;
const EVIDENCE_UNITS=["TEXT","DATE","INSTANT","VND","RATE","COUNT"] as const;
const EXIT_REASONS=["STOP_LOSS","TARGET1","END_OF_PERIOD"] as const;
const ENTRY_OUTCOMES=["REJECTED","CANCELLED"] as const;
export type StrategyCode=typeof STRATEGIES[number];export type RunStatus="QUEUED"|"RUNNING"|"COMPLETED"|"WITHHELD"|"FAILED";
export interface CostPolicy{excluded:boolean;entryFeeRate?:string;exitFeeRate?:string;sellTaxRate?:string;entrySlippageRate?:string;exitSlippageRate?:string}
export interface CreateBacktest{strategyCode:StrategyCode;symbol:string;startDate:string;endDate:string;initialCapitalVnd:string;riskPerTrancheRate:string;maxAggregateOpenRiskRate:string;costs:CostPolicy}
export interface RunSummary{id:string;status:RunStatus;strategyCode:StrategyCode;symbol:string;startDate:string;endDate:string;processedSessions:number;totalSessions:number|null;reasonCode:string|null;createdAt:string;completedAt:string|null}
export interface Metric{code:string;value:string|null;unit:"RATE"|"RATIO"|"COUNT";availability:"DEFINED"|"UNAVAILABLE";reasonCode:string|null;ruleVersion:string}
export interface Evidence{key:string;value:string;unit:string}
export interface RunDetail extends RunSummary{dataCutoffAcceptedAt:string;assumptions:{initialCapitalVnd:string;riskPerTrancheRate:string;maxAggregateOpenRiskRate:string;costs:CostPolicy;strategyRuleVersion:string;sizingRuleVersion:string;engineRuleVersion:string;metricsRuleVersion:string;pyramidingRuleVersion:string;entryTiming:string;sameBarPriority:string;maxOpenTranches:number;pyramidStepAtr:string};metrics:Metric[];evidence:Evidence[];warnings:string[]}
export interface Trade{sequence:number;signalDate:string;entryDate:string;exitDate:string;quantity:number;rawEntryPriceVnd:string;effectiveEntryPriceVnd:string;effectiveExitPriceVnd:string;acquisitionCostVnd:string;netExitProceedsVnd:string;netPnlVnd:string;tradeReturnRate:string;exitReason:string}
export interface EquityPoint{tradingDate:string;cashVnd:string;openPositionValueVnd:string;totalEquityVnd:string;openTrancheCount:number;dailyReturnRate:string|null}
export interface EntryEvent{sequence:number;signalDate:string;executionDate:string|null;outcome:string;reasonCode:string;openTrancheCount:number}
export interface Page<T>{items:T[];total:number;limit:number;offset:number}
export class BacktestApiError extends Error{constructor(readonly status:number,readonly reasonCode:string){super(reasonCode)}}
async function request(url:string,init?:RequestInit):Promise<unknown>{const response=await fetch(url,{credentials:"same-origin",...init});if(!response.ok){const p=await response.json().catch(()=>({})) as {reasonCode?:unknown};throw new BacktestApiError(response.status,typeof p.reasonCode==="string"?p.reasonCode:"SERVER_ERROR")}return await response.json()}
export async function createBacktest(body:CreateBacktest,key=crypto.randomUUID()){const csrf=await getCsrf();return validateRun(await request("/api/v1/backtests",{method:"POST",headers:{"Content-Type":"application/json",Accept:"application/json","Idempotency-Key":key,[csrf.headerName]:csrf.token},body:JSON.stringify(body)}))}
export async function listBacktests(){return parsePage(await request("/api/v1/backtests?limit=100&offset=0"),validateRun)}
export async function getBacktest(id:string){const x=object(await request(`/api/v1/backtests/${id}`));const run=validateRun(x);const dataCutoffAcceptedAt=text(x.dataCutoffAcceptedAt);const assumptions=parseAssumptions(x.assumptions);if(!Array.isArray(x.metrics)||!Array.isArray(x.evidence)||!Array.isArray(x.warnings))throw new Error("Invalid backtest detail");const metrics=x.metrics.map(parseMetric);const evidence=x.evidence.map(parseEvidence);const warnings=x.warnings.map(text);return {...run,dataCutoffAcceptedAt,assumptions,metrics,evidence,warnings}}
export async function getTrades(id:string){return parsePage(await request(`/api/v1/backtests/${id}/trades?limit=5000&offset=0`),v=>{const x=object(v);for(const k of ["sequence","quantity"])integer(x[k]);for(const k of ["signalDate","entryDate","exitDate","rawEntryPriceVnd","effectiveEntryPriceVnd","effectiveExitPriceVnd","acquisitionCostVnd","netExitProceedsVnd","netPnlVnd","tradeReturnRate"])text(x[k]);oneOf(x.exitReason,EXIT_REASONS);return x as unknown as Trade})}
export async function getEquity(id:string){return parsePage(await request(`/api/v1/backtests/${id}/equity?limit=10000&offset=0`),v=>{const x=object(v);text(x.tradingDate);text(x.cashVnd);text(x.openPositionValueVnd);text(x.totalEquityVnd);integer(x.openTrancheCount);if(x.dailyReturnRate!==null)text(x.dailyReturnRate);return x as unknown as EquityPoint})}
export async function getEvents(id:string){return parsePage(await request(`/api/v1/backtests/${id}/events?limit=5000&offset=0`),v=>{const x=object(v);integer(x.sequence);text(x.signalDate);oneOf(x.outcome,ENTRY_OUTCOMES);text(x.reasonCode);integer(x.openTrancheCount);nullableText(x.executionDate);return x as unknown as EntryEvent})}
async function remove(url:string):Promise<void>{const csrf=await getCsrf();const response=await fetch(url,{method:"DELETE",credentials:"same-origin",headers:{Accept:"application/json",[csrf.headerName]:csrf.token}});if(!response.ok){const p=await response.json().catch(()=>({})) as {reasonCode?:unknown};throw new BacktestApiError(response.status,typeof p.reasonCode==="string"?p.reasonCode:"SERVER_ERROR")}}
export async function deleteBacktest(id:string):Promise<void>{await remove(`/api/v1/backtests/${id}`)}
export async function deleteAllBacktests():Promise<void>{await remove("/api/v1/backtests")}
function validateRun(v:unknown):RunSummary{const x=object(v);text(x.id);oneOf(x.strategyCode,STRATEGIES);oneOf(x.status,RUN_STATUSES);for(const k of ["symbol","startDate","endDate","createdAt"])text(x[k]);integer(x.processedSessions);if(x.totalSessions!==null)integer(x.totalSessions);nullableText(x.reasonCode);nullableText(x.completedAt);return x as unknown as RunSummary}
function parseAssumptions(v:unknown):RunDetail["assumptions"]{const x=object(v);for(const k of ["initialCapitalVnd","riskPerTrancheRate","maxAggregateOpenRiskRate","strategyRuleVersion","sizingRuleVersion","engineRuleVersion","metricsRuleVersion","pyramidingRuleVersion","entryTiming","sameBarPriority","pyramidStepAtr"])text(x[k]);integer(x.maxOpenTranches);const costs=parseCosts(x.costs);return {...x,costs} as RunDetail["assumptions"]}
function parseCosts(v:unknown):CostPolicy{const x=object(v);if(typeof x.excluded!=="boolean")throw new Error("Invalid cost policy");for(const k of ["entryFeeRate","exitFeeRate","sellTaxRate","entrySlippageRate","exitSlippageRate"])if(x[k]!==undefined&&x[k]!==null)text(x[k]);return x as unknown as CostPolicy}
function parseMetric(v:unknown):Metric{const x=object(v);oneOf(x.code,METRIC_CODES);oneOf(x.unit,METRIC_UNITS);oneOf(x.availability,AVAILABILITIES);nullableText(x.value);nullableText(x.reasonCode);text(x.ruleVersion);return x as unknown as Metric}
function parseEvidence(v:unknown):Evidence{const x=object(v);text(x.key);text(x.value);oneOf(x.unit,EVIDENCE_UNITS);return x as unknown as Evidence}
function parsePage<T>(v:unknown,parse:(x:unknown)=>T):Page<T>{const x=object(v);if(!Array.isArray(x.items))throw new Error("Invalid page");integer(x.total);integer(x.limit);integer(x.offset);return {items:x.items.map(parse),total:x.total as number,limit:x.limit as number,offset:x.offset as number}}
function object(v:unknown):Record<string,unknown>{if(!v||typeof v!=="object"||Array.isArray(v))throw new Error("Expected object");return v as Record<string,unknown>}
function text(v:unknown):string{if(typeof v!=="string"||v.length===0)throw new Error("Expected text");return v}
function integer(v:unknown):number{if(typeof v!=="number"||!Number.isSafeInteger(v)||v<0)throw new Error("Expected integer");return v}
function nullableText(v:unknown):string|null{if(v===null)return null;return text(v)}
function oneOf<const T extends readonly string[]>(v:unknown,values:T):T[number]{if(typeof v!=="string"||!values.includes(v as T[number]))throw new Error("Unexpected enum value");return v as T[number]}
