package com.minhnb.finvera_be.backtest.domain;
import static org.assertj.core.api.Assertions.assertThat;
import com.minhnb.finvera_be.backtest.domain.BacktestTypes.*;import java.math.BigDecimal;import java.time.*;import java.util.*;import org.junit.jupiter.api.Test;
class BacktestEngineV1Tests{
 private final Assumptions assumptions=new Assumptions(bd("1000000"),bd("0.02"),bd("0.06"),new Costs(bd("0.001"),bd("0.001"),bd("0.001"),bd("0.001"),bd("0.001"),false));
 @Test void signalFillsNextOpenAndStopWinsWhenBothTouched(){var result=BacktestEngineV1.run(List.of(session("2026-01-02",100,101,99,100,true,new BacktestEngineV1.Signal(true,bd("90"),bd("120"),bd("5"))),session("2026-01-05",100,125,85,110,true,new BacktestEngineV1.Signal(false,null,null,null))),assumptions,100);assertThat(result.trades()).hasSize(1);assertThat(result.trades().get(0).entryDate()).isEqualTo(LocalDate.parse("2026-01-05"));assertThat(result.trades().get(0).exitReason()).isEqualTo(ExitReason.STOP_LOSS);assertThat(result.equity().get(1).total()).isEqualByComparingTo(result.trades().get(0).netExitProceeds().add(bd("1000000").subtract(result.trades().get(0).acquisitionCost())));}
 @Test void factorChangeWhilePendingWithholds(){var r=BacktestEngineV1.run(List.of(session("2026-01-02",100,101,99,100,true,new BacktestEngineV1.Signal(true,bd("90"),bd("120"),bd("5"))),barWithFactor("2026-01-05","2")),assumptions,100);assertThat(r.withheldReason()).isEqualTo("CORPORATE_ACTION_UNSUPPORTED");}
 @Test void terminalCloseLeavesNoOpenPosition(){var r=BacktestEngineV1.run(List.of(session("2026-01-02",100,101,99,100,true,new BacktestEngineV1.Signal(true,bd("90"),bd("120"),bd("5"))),session("2026-01-05",100,105,95,103,true,new BacktestEngineV1.Signal(false,null,null,null))),assumptions,100);assertThat(r.trades().get(0).exitReason()).isEqualTo(ExitReason.END_OF_PERIOD);assertThat(r.equity().get(1).openTranches()).isZero();}
 @Test void missingNextOpenCancelsRatherThanShiftingEntry(){var first=session("2026-01-02",100,101,99,100,true,new BacktestEngineV1.Signal(true,bd("90"),bd("120"),bd("5")));var b=session("2026-01-05",100,105,95,103,true,new BacktestEngineV1.Signal(false,null,null,null)).bar();var missing=new BacktestEngineV1.Session(new SessionBar(b.barId(),b.tradingDate(),null,b.rawHigh(),b.rawLow(),b.rawClose(),b.adjustmentFactor(),b.adjustmentStatus(),b.source(),b.observedAt(),b.acceptedAt()),true,new BacktestEngineV1.Signal(false,null,null,null));var r=BacktestEngineV1.run(List.of(first,missing,session("2026-01-06",105,106,104,105,true,new BacktestEngineV1.Signal(false,null,null,null))),assumptions,100);assertThat(r.trades()).isEmpty();assertThat(r.events()).singleElement().extracting(BacktestEngineV1.Event::reasonCode).isEqualTo("EXECUTION_PRICE_UNAVAILABLE");}
 private static BacktestEngineV1.Session barWithFactor(String d,String f){var s=session(d,100,101,99,100,true,new BacktestEngineV1.Signal(false,null,null,null));var b=s.bar();return new BacktestEngineV1.Session(new SessionBar(b.barId(),b.tradingDate(),b.rawOpen(),b.rawHigh(),b.rawLow(),b.rawClose(),bd(f),"ADJUSTED","TEST",b.observedAt(),b.acceptedAt()),true,s.signal());}
 private static BacktestEngineV1.Session session(String d,int o,int h,int l,int c,boolean report,BacktestEngineV1.Signal signal){LocalDate date=LocalDate.parse(d);return new BacktestEngineV1.Session(new SessionBar(UUID.randomUUID(),date,bd(""+o),bd(""+h),bd(""+l),bd(""+c),bd("1"),"ADJUSTED","TEST",date.atStartOfDay(ZoneOffset.UTC).toInstant(),date.atStartOfDay(ZoneOffset.UTC).toInstant()),report,signal);}
 private static BigDecimal bd(String x){return new BigDecimal(x);}
}
