package com.minhnb.finvera_be.stock.service;
import com.minhnb.finvera_be.stock.domain.model.StockTypes.*;import com.minhnb.finvera_be.stock.domain.technical.TechnicalIndicatorsV1;import com.minhnb.finvera_be.stock.entity.*;import com.minhnb.finvera_be.stock.repository.*;import java.math.BigDecimal;import java.time.*;import java.util.*;import java.util.stream.Collectors;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
/** Published read-only source-fact boundary for Feature 032. */
@Service public class StockAlertDataService{
 private final EquityDailyBarRepository bars;private final TechnicalIndicatorResultRepository results;private final TechnicalIndicatorValueRepository values;private final StockReferenceDataService refs;
 public StockAlertDataService(EquityDailyBarRepository b,TechnicalIndicatorResultRepository r,TechnicalIndicatorValueRepository v,StockReferenceDataService s){bars=b;results=r;values=v;refs=s;}
 public record Bar(UUID id,LocalDate date,BigDecimal high,BigDecimal low,BigDecimal close,long volume,String basis,String source,Instant observedAt,Instant acceptedAt){}
 public record Indicator(UUID id,LocalDate date,String code,String ruleVersion,String basis,String status,String reason,Instant acceptedAt,Map<String,BigDecimal> components){}
 public record Snapshot(List<Bar> bars,List<Indicator> indicators,List<StockReferenceDataService.SignalReference> signals){}
 @Transactional(readOnly=true)public Snapshot resolve(UUID instrumentId){var br=bars.findLatestNCurrentByInstrumentIdIn(List.of(instrumentId),22).stream().map(b->new Bar(b.getId(),b.getTradingDate(),b.getHighPrice(),b.getLowPrice(),b.getClosePrice(),b.getVolume()==null?0:b.getVolume(),b.getAdjustmentStatus(),b.getSource(),b.getObservedAt(),b.getAcceptedAt())).toList();var rr=results.findLatestNCurrentByInstrumentIdInAndRuleVersion(List.of(instrumentId),TechnicalIndicatorsV1.RULE_VERSION,2);var by=values.findByResultIdIn(rr.stream().map(TechnicalIndicatorResultEntity::getId).toList()).stream().collect(Collectors.groupingBy(TechnicalIndicatorValueEntity::getResultId));var ii=rr.stream().map(r->new Indicator(r.getId(),r.getAsOfTradingDate(),r.getIndicatorCode(),r.getRuleVersion(),r.getAdjustmentStatus(),r.getDataStatus(),r.getQualityReason(),r.getCalculatedAt(),by.getOrDefault(r.getId(),List.of()).stream().collect(Collectors.toMap(TechnicalIndicatorValueEntity::getComponentCode,TechnicalIndicatorValueEntity::getValue)))).toList();return new Snapshot(br,ii,refs.findCurrentSignalsForInstruments(List.of(instrumentId)));}
}
