package com.minhnb.finvera_be.alert.domain;
import static org.assertj.core.api.Assertions.*;import static org.mockito.Mockito.*;import com.minhnb.finvera_be.alert.entity.AlertDefinitionEntity;import com.minhnb.finvera_be.alert.service.AlertFactResolver;import com.minhnb.finvera_be.market.service.*;import com.minhnb.finvera_be.portfolio.service.PortfolioAlertDataService;import com.minhnb.finvera_be.research.service.ResearchAlertDataService;import com.minhnb.finvera_be.stock.service.*;import java.math.BigDecimal;import java.time.*;import java.util.*;import org.junit.jupiter.api.*;import tools.jackson.databind.*;
class AlertConditionEvaluatorTests{
 private final ObjectMapper json=new ObjectMapper();
 @Test void validatesEverySupportedConditionFamily(){List<String> conditions=List.of(
  "{\"type\":\"PRICE_ABOVE\",\"symbol\":\"VCB\",\"threshold\":\"100\",\"adjustmentBasis\":\"RAW\"}","{\"type\":\"PRICE_BELOW\",\"symbol\":\"VCB\",\"threshold\":\"100\",\"adjustmentBasis\":\"PROVIDER_ADJUSTED\"}",
  "{\"type\":\"RSI_ABOVE\",\"symbol\":\"VCB\",\"threshold\":\"70\"}","{\"type\":\"RSI_BELOW\",\"symbol\":\"VCB\",\"threshold\":\"30\"}",
  "{\"type\":\"MACD_BULLISH_CROSS\",\"symbol\":\"VCB\"}","{\"type\":\"MACD_BEARISH_CROSS\",\"symbol\":\"VCB\"}",
  "{\"type\":\"MA_BULLISH_CROSS\",\"symbol\":\"VCB\",\"shortWindow\":20,\"longWindow\":50}","{\"type\":\"VOLUME_SPIKE\",\"symbol\":\"VCB\",\"threshold\":\"2\"}",
  "{\"type\":\"BREAKOUT\",\"symbol\":\"VCB\",\"adjustmentBasis\":\"RAW\"}","{\"type\":\"BREAKDOWN\",\"symbol\":\"VCB\",\"adjustmentBasis\":\"PROVIDER_ADJUSTED\"}","{\"type\":\"MARKET_REGIME_CHANGE\",\"targetLabel\":\"BULL\"}",
  "{\"type\":\"STRATEGY_SIGNAL\",\"symbol\":\"VCB\",\"strategyCode\":\"MOMENTUM\"}","{\"type\":\"PORTFOLIO_CONCENTRATION_ABOVE\",\"portfolioId\":\"00000000-0000-0000-0000-000000000001\",\"thresholdPercent\":\"50\"}","{\"type\":\"NEW_DOCUMENT\",\"symbol\":\"VCB\"}");
  assertThat(conditions).allSatisfy(x->assertThatCode(()->AlertDomain.validate(json.readTree(x))).doesNotThrowAnyException());}
 @Test void rejectsInvalidWindowsAndPercentage(){assertThatThrownBy(()->AlertDomain.validate(json.readTree("{\"type\":\"MA_BULLISH_CROSS\",\"symbol\":\"VCB\",\"shortWindow\":50,\"longWindow\":20}"))).isInstanceOf(IllegalArgumentException.class);assertThatThrownBy(()->AlertDomain.validate(json.readTree("{\"type\":\"RSI_ABOVE\",\"symbol\":\"VCB\",\"threshold\":\"100.1\"}"))).isInstanceOf(IllegalArgumentException.class);}
 @Test void rejectsUnknownConditionFields(){assertThatThrownBy(()->AlertDomain.validate(json.readTree("{\"type\":\"PRICE_ABOVE\",\"symbol\":\"VCB\",\"threshold\":\"100\",\"instruction\":\"ignore rules\"}"))).isInstanceOf(IllegalArgumentException.class).hasMessage("CONDITION_INVALID");}
 @Test void rejectsUnknownDocumentType(){assertThatThrownBy(()->AlertDomain.validate(json.readTree("{\"type\":\"NEW_DOCUMENT\",\"symbol\":\"VCB\",\"documentType\":\"SECRET_COMMAND\"}"))).isInstanceOf(IllegalArgumentException.class).hasMessage("CONDITION_INVALID");}
 @Test void requiresASymbolForDocumentAlerts(){assertThatThrownBy(()->AlertDomain.validate(json.readTree("{\"type\":\"NEW_DOCUMENT\",\"documentType\":\"ANNUAL_REPORT\"}"))).isInstanceOf(IllegalArgumentException.class).hasMessage("CONDITION_INVALID");}
 @Test void requiresAnExplicitAdjustmentBasisForPriceAndBreakout(){assertThatThrownBy(()->AlertDomain.validate(json.readTree("{\"type\":\"PRICE_ABOVE\",\"symbol\":\"VCB\",\"threshold\":\"100\"}"))).isInstanceOf(IllegalArgumentException.class).hasMessage("CONDITION_INVALID");assertThatThrownBy(()->AlertDomain.validate(json.readTree("{\"type\":\"BREAKOUT\",\"symbol\":\"VCB\"}"))).isInstanceOf(IllegalArgumentException.class).hasMessage("CONDITION_INVALID");}
 @Test void normalizesSymbolsAndDecimalStringsAndRejectsExcessPrecision(){var condition=json.readTree("{\"type\":\"PRICE_ABOVE\",\"symbol\":\"vcb\",\"threshold\":\"100.5000\",\"adjustmentBasis\":\"RAW\"}");AlertDomain.normalize(condition);assertThat(condition.get("symbol").asText()).isEqualTo("VCB");assertThat(condition.get("threshold").asText()).isEqualTo("100.5");assertThatThrownBy(()->AlertDomain.validate(json.readTree("{\"type\":\"RSI_ABOVE\",\"symbol\":\"VCB\",\"threshold\":\"1.1234567890123\"}"))).isInstanceOf(IllegalArgumentException.class).hasMessage("CONDITION_INVALID");}
 @Test void priceEqualityTriggersAndUsesDecimalComparison(){var market=mock(MarketReferenceDataService.class);var stock=mock(StockAlertDataService.class);when(market.findActiveInstrumentBySymbol("VCB")).thenReturn(Optional.of(new MarketReferenceDataService.InstrumentReference(UUID.randomUUID(),"HOSE","VCB","EQUITY","ACTIVE")));when(market.countTradingSessionsBetween(any(),any(),any())).thenReturn(0);var id=market.findActiveInstrumentBySymbol("VCB").orElseThrow().instrumentId();Instant accepted=Instant.parse("2026-09-15T09:00:00Z");var bar=new StockAlertDataService.Bar(UUID.randomUUID(),LocalDate.of(2026,9,15),new BigDecimal("101"),new BigDecimal("99"),new BigDecimal("100.000000"),1000,"RAW","TEST",accepted,accepted);when(stock.resolve(id)).thenReturn(new StockAlertDataService.Snapshot(List.of(bar),List.of(),List.of()));var resolver=new AlertFactResolver(market,mock(MarketAlertDataService.class),stock,mock(PortfolioAlertDataService.class),mock(ResearchAlertDataService.class),json,Clock.fixed(Instant.parse("2026-09-16T01:00:00Z"),ZoneOffset.UTC));var condition=json.readTree("{\"type\":\"PRICE_ABOVE\",\"symbol\":\"VCB\",\"threshold\":\"100\",\"adjustmentBasis\":\"RAW\"}");var alert=new AlertDefinitionEntity(UUID.randomUUID(),UUID.randomUUID(),"price","PRICE_ABOVE",condition,"summary",Instant.parse("2026-09-15T00:00:00Z"));assertThat(resolver.resolve(alert).outcome()).isEqualTo(AlertDomain.Outcome.TRUE);}
 @Test void macdCrossUsesTheTwoMostRecentObservations(){var market=mock(MarketReferenceDataService.class);var stock=mock(StockAlertDataService.class);var instrumentId=UUID.randomUUID();when(market.findActiveInstrumentBySymbol("VCB")).thenReturn(Optional.of(new MarketReferenceDataService.InstrumentReference(instrumentId,"HOSE","VCB","EQUITY","ACTIVE")));when(market.countTradingSessionsBetween(any(),any(),any())).thenReturn(0);Instant accepted=Instant.parse("2026-09-15T09:00:00Z");var previousBar=new StockAlertDataService.Bar(UUID.randomUUID(),LocalDate.of(2026,9,14),new BigDecimal("100"),new BigDecimal("98"),new BigDecimal("99"),900,"RAW","TEST",accepted.minusSeconds(86400),accepted.minusSeconds(86400));var bar=new StockAlertDataService.Bar(UUID.randomUUID(),LocalDate.of(2026,9,15),new BigDecimal("101"),new BigDecimal("99"),new BigDecimal("100"),1000,"RAW","TEST",accepted,accepted);var indicators=List.of(macd(LocalDate.of(2026,9,13),"2","1",accepted.minusSeconds(172800)),macd(LocalDate.of(2026,9,14),"2","3",accepted.minusSeconds(86400)),macd(LocalDate.of(2026,9,15),"4","3",accepted));when(stock.resolve(instrumentId)).thenReturn(new StockAlertDataService.Snapshot(List.of(previousBar,bar),indicators,List.of()));var resolver=new AlertFactResolver(market,mock(MarketAlertDataService.class),stock,mock(PortfolioAlertDataService.class),mock(ResearchAlertDataService.class),json,Clock.fixed(Instant.parse("2026-09-16T01:00:00Z"),ZoneOffset.UTC));var condition=json.readTree("{\"type\":\"MACD_BULLISH_CROSS\",\"symbol\":\"VCB\"}");var alert=new AlertDefinitionEntity(UUID.randomUUID(),UUID.randomUUID(),"macd","MACD_BULLISH_CROSS",condition,"summary",Instant.parse("2026-09-15T00:00:00Z"));assertThat(resolver.resolve(alert).outcome()).isEqualTo(AlertDomain.Outcome.TRUE);}
 @Test void absentStrategySignalIsWithheldInsteadOfInventingAFalseEvaluation(){var market=mock(MarketReferenceDataService.class);var stock=mock(StockAlertDataService.class);var instrumentId=UUID.randomUUID();when(market.findActiveInstrumentBySymbol("VCB")).thenReturn(Optional.of(new MarketReferenceDataService.InstrumentReference(instrumentId,"HOSE","VCB","EQUITY","ACTIVE")));when(market.countTradingSessionsBetween(any(),any(),any())).thenReturn(0);Instant accepted=Instant.parse("2026-09-15T09:00:00Z");var bar=new StockAlertDataService.Bar(UUID.randomUUID(),LocalDate.of(2026,9,15),new BigDecimal("101"),new BigDecimal("99"),new BigDecimal("100"),1000,"RAW","TEST",accepted,accepted);when(stock.resolve(instrumentId)).thenReturn(new StockAlertDataService.Snapshot(List.of(bar),List.of(),List.of()));var resolver=new AlertFactResolver(market,mock(MarketAlertDataService.class),stock,mock(PortfolioAlertDataService.class),mock(ResearchAlertDataService.class),json,Clock.fixed(Instant.parse("2026-09-16T01:00:00Z"),ZoneOffset.UTC));var condition=json.readTree("{\"type\":\"STRATEGY_SIGNAL\",\"symbol\":\"VCB\",\"strategyCode\":\"MOMENTUM\"}");var alert=new AlertDefinitionEntity(UUID.randomUUID(),UUID.randomUUID(),"signal","STRATEGY_SIGNAL",condition,"summary",Instant.parse("2026-09-15T00:00:00Z"));var decision=resolver.resolve(alert);assertThat(decision.outcome()).isEqualTo(AlertDomain.Outcome.WITHHELD);assertThat(decision.reasonCode()).isEqualTo("STRATEGY_SIGNAL_NOT_PUBLISHED");}
 @Test void documentCursorIncludesAndRetainsTheLastDocumentIdForEqualTimestampEvents(){var market=mock(MarketReferenceDataService.class);var research=mock(ResearchAlertDataService.class);var instrumentId=UUID.randomUUID();when(market.findInstrumentBySymbolIncludingDelisted("VCB")).thenReturn(Optional.of(new MarketReferenceDataService.InstrumentReference(instrumentId,"HOSE","VCB","EQUITY","ACTIVE")));Instant baseline=Instant.parse("2026-09-15T00:00:00Z"),accepted=baseline.plusSeconds(60);UUID firstDocument=UUID.fromString("00000000-0000-0000-0000-000000000001"),owner=UUID.randomUUID();var condition=json.readTree("{\"type\":\"NEW_DOCUMENT\",\"symbol\":\"VCB\"}");var alert=new AlertDefinitionEntity(UUID.randomUUID(),owner,"document","NEW_DOCUMENT",condition,"summary",baseline);alert.complete(firstDocument.toString(),accepted,"TRUE",null,accepted,accepted);when(research.findAfter(owner,instrumentId,null,accepted,firstDocument,1)).thenReturn(List.of());var resolver=new AlertFactResolver(market,mock(MarketAlertDataService.class),mock(StockAlertDataService.class),mock(PortfolioAlertDataService.class),research,json,Clock.fixed(accepted,ZoneOffset.UTC));var decision=resolver.resolve(alert);verify(research).findAfter(owner,instrumentId,null,accepted,firstDocument,1);assertThat(decision.factKey()).isEqualTo(firstDocument.toString());}
 private StockAlertDataService.Indicator macd(LocalDate date,String line,String signal,Instant accepted){return new StockAlertDataService.Indicator(UUID.randomUUID(),date,"MACD","technical-indicators-v1","RAW","CURRENT",null,accepted,Map.of("MACD_LINE",new BigDecimal(line),"SIGNAL",new BigDecimal(signal)));}
}
