package com.minhnb.finvera_be.portfolio.service;
import com.minhnb.finvera_be.market.service.MarketReferenceDataService;import com.minhnb.finvera_be.portfolio.domain.analytics.PortfolioAnalyticsV1;import com.minhnb.finvera_be.portfolio.repository.*;import com.minhnb.finvera_be.stock.service.StockReferenceDataService;import java.math.*;import java.time.*;import java.util.*;import java.util.stream.Collectors;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
/** Owner-explicit application boundary used by the background alert worker. */
@Service public class PortfolioAlertDataService{
 private final PortfolioRepository portfolios;private final PortfolioTransactionRepository txs;private final MarketReferenceDataService market;private final StockReferenceDataService stock;private final Clock clock;
 public PortfolioAlertDataService(PortfolioRepository p,PortfolioTransactionRepository t,MarketReferenceDataService m,StockReferenceDataService s,Clock c){portfolios=p;txs=t;market=m;stock=s;clock=c;}
 public record Snapshot(BigDecimal percentage,String largestSymbol,Instant observedAt,String status,String reason,String ruleVersion,String factKey){}
 @Transactional(readOnly=true)public boolean existsOwned(UUID owner,UUID portfolioId){return portfolios.findByIdAndOwnerIdAndDeletedAtIsNull(portfolioId,owner).isPresent();}
 @Transactional(readOnly=true)public Snapshot resolve(UUID owner,UUID portfolioId){if(portfolios.findByIdAndOwnerIdAndDeletedAtIsNull(portfolioId,owner).isEmpty())return new Snapshot(null,null,clock.instant(),"UNAVAILABLE","TARGET_NOT_AVAILABLE","portfolio-concentration-v1","portfolio:"+portfolioId);var raw=txs.findByPortfolioIdOrderByExecutedAtAscSequenceNoAsc(portfolioId);if(raw.isEmpty())return unavailable(portfolioId,"NO_POSITIONS");var ids=raw.stream().map(x->x.getInstrumentId()).collect(Collectors.toSet());var instruments=market.findInstrumentsByIds(ids);var byId=instruments.stream().collect(Collectors.toMap(MarketReferenceDataService.InstrumentReference::instrumentId,x->x));var symbols=instruments.stream().collect(Collectors.toMap(MarketReferenceDataService.InstrumentReference::instrumentId,MarketReferenceDataService.InstrumentReference::symbol));var barList=stock.findLatestDailyBars(ids);var prices=barList.stream().collect(Collectors.toMap(StockReferenceDataService.DailyBarReference::instrumentId,StockReferenceDataService.DailyBarReference::closePrice));var state=PortfolioAnalyticsV1.replayHoldings(raw.stream().map(x->PositionService.toTransactionInput(x,symbols.get(x.getInstrumentId()))).toList(),prices,symbols);var open=state.positions().values().stream().filter(x->x.quantity().signum()>0).toList();if(open.isEmpty())return unavailable(portfolioId,"NO_POSITIONS");if(open.stream().anyMatch(x->x.marketValue()==null))return unavailable(portfolioId,"PARTIAL_PRICE_DATA");var openSymbols=open.stream().map(PortfolioAnalyticsV1.PositionResult::symbol).collect(Collectors.toSet());LocalDate today=LocalDate.now(clock.withZone(ZoneId.of("Asia/Ho_Chi_Minh")));if(barList.stream().filter(b->{var instrument=byId.get(b.instrumentId());return instrument!=null&&openSymbols.contains(instrument.symbol());}).anyMatch(b->{var instrument=byId.get(b.instrumentId());return market.countTradingSessionsBetween(instrument.venue(),b.tradingDate(),today)>1;}))return unavailable(portfolioId,"PRICE_DATA_STALE");BigDecimal total=open.stream().map(PortfolioAnalyticsV1.PositionResult::marketValue).reduce(BigDecimal.ZERO,BigDecimal::add);if(total.signum()<=0)return unavailable(portfolioId,"NO_INVESTED_VALUE");var largest=open.stream().max(Comparator.comparing(PortfolioAnalyticsV1.PositionResult::marketValue)).orElseThrow();BigDecimal pct=largest.marketValue().multiply(new BigDecimal("100")).divide(total,12,RoundingMode.HALF_UP);Instant accepted=barList.stream().map(StockReferenceDataService.DailyBarReference::acceptedAt).filter(Objects::nonNull).min(Instant::compareTo).orElse(clock.instant());String key="portfolio:"+portfolioId+":"+barList.stream().map(b->b.id().toString()).sorted().collect(Collectors.joining(","));return new Snapshot(pct,largest.symbol(),accepted,"CURRENT",null,"portfolio-concentration-v1",key);}
 private Snapshot unavailable(UUID id,String reason){return new Snapshot(null,null,clock.instant(),"UNAVAILABLE",reason,"portfolio-concentration-v1","portfolio:"+id+":"+reason);}
}
