import {useCallback,useEffect,useState,type FormEvent} from "react";
import {Bell,Plus,Trash2} from "lucide-react";
import * as api from "../api/alerts";

const TYPES=["PRICE_ABOVE","PRICE_BELOW","RSI_ABOVE","RSI_BELOW","MACD_BULLISH_CROSS","MACD_BEARISH_CROSS","MA_BULLISH_CROSS","MA_BEARISH_CROSS","VOLUME_SPIKE","BREAKOUT","BREAKDOWN","MARKET_REGIME_CHANGE","STRATEGY_SIGNAL","PORTFOLIO_CONCENTRATION_ABOVE","NEW_DOCUMENT"];
const errorReason=(value:unknown)=>value instanceof api.AlertApiError?value.reasonCode:"Không thể xử lý cảnh báo";

export function AlertsPage(){
 const[alerts,setAlerts]=useState<api.Alert[]>([]),[notices,setNotices]=useState<api.Notification[]>([]),[evaluations,setEvaluations]=useState<api.Evaluation[]>([]);
 const[selected,setSelected]=useState<string|null>(null),[unread,setUnread]=useState(0),[error,setError]=useState<string|null>(null),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{try{const[a,n,u]=await Promise.all([api.listAlerts(),api.listNotifications(),api.unreadCount()]);setAlerts(a.items);setNotices(n.items);setUnread(u.count);setError(null)}catch(e){setError(errorReason(e))}},[]);
 useEffect(()=>{const initial=window.setTimeout(()=>void load(),0);const id=window.setInterval(()=>void load(),10_000);return()=>{clearTimeout(initial);clearInterval(id)}},[load]);
 async function run(action:()=>Promise<unknown>){setBusy(true);try{await action();await load()}catch(e){setError(errorReason(e))}finally{setBusy(false)}}
 async function history(id:string){try{const page=await api.listEvaluations(id);setSelected(id);setEvaluations(page.items)}catch(e){setError(errorReason(e))}}
 async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,f=new FormData(form),type=String(f.get("type")),name=String(f.get("name")),target=String(f.get("symbol")||""),symbol=target.toUpperCase(),value=String(f.get("value")||"");let condition:api.Condition={type};if(type.includes("PRICE"))condition={...condition,symbol,threshold:value,adjustmentBasis:"RAW"};else if(type.includes("RSI")||type==="VOLUME_SPIKE")condition={...condition,symbol,threshold:value};else if(type.startsWith("MACD"))condition={...condition,symbol};else if(type==="BREAKOUT"||type==="BREAKDOWN")condition={...condition,symbol,adjustmentBasis:"RAW"};else if(type.startsWith("MA_"))condition={...condition,symbol,shortWindow:20,longWindow:50};else if(type==="MARKET_REGIME_CHANGE")condition={...condition,targetLabel:value||"BULL"};else if(type==="STRATEGY_SIGNAL")condition={...condition,symbol,strategyCode:value||"TREND_FOLLOWING"};else if(type==="PORTFOLIO_CONCENTRATION_ABOVE")condition={...condition,portfolioId:target,thresholdPercent:value};else condition={...condition,symbol:symbol||undefined,documentType:value||undefined};await run(async()=>{await api.createAlert(name,condition);form.reset()})}
 return <main className="page-shell">
  <header className="page-header"><div><p className="eyebrow">AUTOMATION · DETERMINISTIC</p><h1>Cảnh báo</h1><p>Theo dõi dữ liệu phiên hoàn tất và lưu bằng chứng cho từng lần kích hoạt.</p></div><div className="status-pill"><Bell size={15}/> {unread} chưa đọc</div></header>
  {error&&<p role="alert" className="error-card">{error}</p>}
  <section className="terminal-panel"><h2>Tạo cảnh báo</h2><form onSubmit={create} className="grid gap-3 md:grid-cols-5"><label>Tên<input name="name" required maxLength={120}/></label><label>Điều kiện<select name="type">{TYPES.map(x=><option key={x}>{x}</option>)}</select></label><label>Mã / Portfolio ID<input name="symbol" placeholder="VCB"/></label><label>Ngưỡng / nhãn<input name="value" placeholder="70000"/></label><button className="btn-primary self-end" disabled={busy}><Plus size={14}/>Tạo</button></form></section>
  <div className="grid gap-5 xl:grid-cols-2"><section className="terminal-panel"><h2>Định nghĩa ({alerts.length})</h2>{alerts.length===0?<p>Chưa có cảnh báo.</p>:alerts.map(a=><article key={a.id} className="border-b border-slate-800 py-3"><div className="flex justify-between gap-3"><div><strong>{a.name}</strong><p>{a.conditionSummary}</p><small>{a.enabled?"Đang bật":"Đã tắt"} · episode {a.episodeState} · {a.latestEvaluation?.outcome??"Chưa đánh giá"}{a.latestEvaluation?.reasonCode?` (${a.latestEvaluation.reasonCode})`:""}</small></div><div className="flex gap-2"><button disabled={busy} onClick={()=>void run(()=>api.setAlertState(a.id,!a.enabled))}>{a.enabled?"Tắt":"Bật"}</button><button onClick={()=>void history(a.id)}>Lịch sử</button><button disabled={busy} aria-label={`Xóa ${a.name}`} onClick={()=>void run(()=>api.deleteAlert(a.id))}><Trash2 size={14}/></button></div></div>{selected===a.id&&<div className="mt-3" aria-label={`Lịch sử ${a.name}`}>{evaluations.length===0?<p>Chưa có lần đánh giá.</p>:evaluations.map(x=><details key={x.id}><summary>{new Date(x.evaluatedAt).toLocaleString("vi-VN")} · {x.outcome}{x.reasonCode?` (${x.reasonCode})`:""}</summary><pre className="overflow-auto text-xs">{JSON.stringify(x.evidence,null,2)}</pre></details>)}</div>}</article>)}</section>
   <section className="terminal-panel"><div className="flex justify-between"><h2>Hộp thư</h2><button disabled={!unread||busy} onClick={()=>void run(api.markAllRead)}>Đánh dấu tất cả đã đọc</button></div>{notices.length===0?<p>Chưa có thông báo.</p>:notices.map(n=><article key={n.id} className="border-b border-slate-800 py-3"><button className="block w-full text-left" disabled={busy} onClick={()=>void run(()=>api.markRead(n.id))}><strong>{n.readAt?"":"● "}{n.title}</strong><p>{n.message}</p><small>{new Date(n.deliveredAt).toLocaleString("vi-VN")}</small></button><details><summary>Bằng chứng</summary><pre className="overflow-auto text-xs">{JSON.stringify(n.evidence,null,2)}</pre></details></article>)}</section>
  </div>
 </main>
}
